apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oz8s4zpvq-nodejs
  janus-idp.io/tekton: oz8s4zpvq-nodejs
  backstage.io/kubernetes-id: oz8s4zpvq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oz8s4zpvq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
